name: 'autoapprove'
description: 'Automatically approve PRs'
inputs:
  github_token:
    description: 'API Token for Github'
    required: true
  user_to_approve:
    description: 'Username or token of PR authors that should be automatically approved'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Approve"
      shell: bash
      run: |
        user="${{ inputs.user_to_approve }}"
        case "$user" in
          ghp_*) user="$(curl --no-progress-meter -H "Authorization: token $user" https://api.github.com/user | jq -r .login)";;
          *) ;;
        esac
        github() {
          curl --no-progress-meter -H "Authorization: token ${{ inputs.github_token }}" https://api.github.com"$@"
        }
        ([ -n "${{ github.event.pull_request.number }}" ] && github /repos/"${{ github.repository }}"/pulls/"${{ github.event.pull_request.number }}" | jq --unbuffered -s || github /repos/"${{ github.repository }}"/pulls?per_page=100) \
          | jq --unbuffered '.[] | select(.state == "open") | select(.user.login == "'"$user"'") | .number' \
          | while read -r pr_number; do
            [ "$(github /repos/"${{ github.repository }}"/pulls/"$pr_number"/reviews | jq --unbuffered -r '.[] | select(.state == "APPROVED") | .id' | wc -l)" = "0" ] && echo "$pr_number" || true
          done | while read -r pr_number; do
            if [ "$(github /repos/"${{ github.repository }}"/pulls/"$pr_number"/commits'?per_page=100' | jq '.[] | [ .committer.login, .author.login ] | @tsv' -r | sed 's/\t/\n/g' | sort -u)" = "$user" ] && echo "$pr_number" || true
          done | while read -r pr_number; do
            echo "::notice ::Autoapproving https://github.com/${{ github.repository }}/pulls/$pr_number"
            github /repos/"${{ github.repository }}"/pulls/"$pr_number"/reviews -d '{"event":"APPROVE","body":"This is an automated approval."}'
          done
