name: Autoapprove

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: plengauer/autoapprove@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_to_approve: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
