name: Autoapprove

on:
  pull_request:
  workflow_dispatch:

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/job@v5.12.1
        with:
          secrets_to_redact: '${{ toJSON(secrets) }}'
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
      - uses: plengauer/autoapprove@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_to_approve: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
