name: Autoapprove

on:
  pull_request:
  workflow_dispatch:

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: plengauer/autoapprove@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_to_approve: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
